name: cli-draw

on:
  push:
    branches: ["main"]
    tags: ["v*"]

  pull_request:
    branches: ["main"]

jobs:
    build:
        runs-on: "ubuntu-latest"

        steps:
            - uses: actions/checkout@v6

            - name: Install uv
              uses: astral-sh/setup-uv@v6
            
            - name: Set up python
              run: uv python install
            
            - name: sync dependencies
              run: uv sync
            
            - name: make dist dir
              run: mkdir -p dist
            
            - name: build the tool
              run: uv build --out-dir dist
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist
                path: dist/*
            
    release:
        needs: build
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v5
              with:
                path: dist

            - name: Flatten files
              run: |
                mkdir -p release
                find dist -type f -exec mv {} release/ \;

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                files: release/*